export const FETCH_COUNTRIES = 'FETCH_COUNTRIES'
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS'
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE'

export const FETCH_WORLD = 'FETCH_WORLD'
export const FETCH_WORLD_SUCCESS = 'FETCH_WORLD_SUCCESS'
export const FETCH_WORLD_FAILURE = 'FETCH_WORLD_FAILURE'
export const FETCH_WORLD_YESTERDAY_SUCCESS = 'FETCH_WORLD_YESTERDAY_SUCCESS'
export const FETCH_WORLD_YESTERDAY_FAILURE = 'FETCH_WORLD_YESTERDAY_FAILURE'


export const FETCH_SPAIN = 'FETCH_SPAIN'
export const FETCH_SPAIN_SUCCESS = 'FETCH_SPAIN_SUCCESS'
export const FETCH_SPAIN_FAILURE = 'FETCH_SPAIN_FAILURE'

export const FETCH_SPAIN_HISTORICAL = 'FETCH_SPAIN_HISTORICAL'
export const FETCH_SPAIN_HISTORICAL_CONFIRMED = 'FETCH_SPAIN_HISTORICAL_CONFIRMED'
export const FETCH_SPAIN_HISTORICAL_RECOVERED = 'FETCH_SPAIN_HISTORICAL_RECOVERED'
export const FETCH_SPAIN_HISTORICAL_CRITICAL = 'FETCH_SPAIN_HISTORICAL_CRITICAL'
export const FETCH_SPAIN_HISTORICAL_DEATHS = 'FETCH_SPAIN_HISTORICAL_DEATHS'
export const FETCH_SPAIN_HISTORICAL_FAILURE = 'FETCH_SPAIN_HISTORICAL_FAILURE'